### ISSUE TITLE
urlUtils and itemUtils: application-level modules?

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-base-js#12]
I wonder if these are really an app-level or an app-base module?  

urlUtils seems to be forcing the url/param structure to be a certain pattern and it should be up to the app to decide this. It's also loading libraries that I might not need to load. e.g. camera

https://github.com/Esri/application-base-js/blob/a7a3eecd54389739e8c2af6ed9643913cb12efdb/support/urlUtils.ts

itemUtils beyond this seems app-level too.

https://github.com/Esri/application-base-js/blob/master/support/itemUtils.js#L108

Move to app-template-examples?

@driskull @kellyhutchins

**Comment by kellyhutchins** [comment]
Those are the standard url parameters from ArcGIS Online that we'd like all the configurable apps to support so my vote is that they stay in app base.

**Comment by alaframboise** [comment]
Thanks @kellyhutchins. I wish I would have known this as I use totally different params to configure the view, marker, search... 

Is this documented somewhere?

**Comment by kellyhutchins** [comment]
Probably not. We had an issue in devtopia for the app developers when we first started supporting the url params and then we added the urlUtils support to the boilerplate.

**Comment by alaframboise** [comment]
Is this what the Map Viewer uses/will use in the future?

**Comment by kellyhutchins** [comment]
The parameters themselves are doc'd in ArcGIS Online doc. 
http://doc.arcgis.com/en/arcgis-online/reference/use-url-parameters.htm 

Although we don't use all of them.

**Comment by alaframboise** [comment]
Oh man. I don't use extent at all and use center, scale, zoom... since the map and view has changed a lot at 4.x. 

There's other stuff in there too that can conflict with apps.  E.g. my app uses and clears the view.graphics...

https://github.com/Esri/application-base-js/blob/master/support/itemUtils.js#L109

Plus I also see this in here for loading the view (but not in the AGO doc). I did this totally differently...

https://github.com/Esri/application-base-js/blob/master/support/itemUtils.js#L38

**Comment by alaframboise** [comment]
And for basemap url params, we might want to add something to accept the actual name string. e.g. `streets-vector`

**Comment by driskull** [comment]
@alaframboise if you don't want the mixins, you don't have to use them. They are all apart of the helper methods your app doesn't have to call.
