### ISSUE TITLE
urlUtils: Pass in component options with parameters

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-base-js#13]
Maybe we can create a structure here where components can have position? 

e.g. "top-right"

https://github.com/Esri/application-base-js/blob/master/support/urlUtils.ts#L48

**Comment by driskull** [comment]
It would be dependent on the View UI props. https://developers.arcgis.com/javascript/latest/api-reference/esri-views-ui-DefaultUI.html#components

**Comment by alaframboise** [comment]
So should it be: ```components=[{0,top-left,zoom},{0,bottom-left,compass}]```?

**Comment by driskull** [comment]
@alaframboise open an issue for the JSAPI first. We can't do it until its supported in the API.

**Comment by alaframboise** [comment]
@driskull I'm not clear why we need an API issue. This is the same as creating a camera and viewpoint - you have decompose the URL and build up the objects with the JS API. In this case it might look something like this:

```
componentsUrl.foreach(function(item)) {
  var component = createComponent(item[2])
  view.ui.add([
  {
    component: component,
    position: item[1],
    index: item[0]
  });
});
```

**Comment by driskull** [comment]
@alaframboise because the API provides an easy way to add components. I don't want to build a different version of it in the boilerplate.

**Comment by alaframboise** [comment]
@driskull might be good to include something like this in one of the default boilerplate samples?

**Comment by kellyhutchins** [comment]
@alaframboise sure if you think it will be a commonly used pattern we can easily update a sample to show this. Feel free to submit a pull request with the new sample - or revision to an existing one. 

Thanks
