### ISSUE TITLE
urlUtils: Add remaining Map Viewer URL support for layers

### ISSUE THREAD

**Issue by alaframboise** [Esri/application-base-js#14]
urlUtils supports most of the MapViewer URL parameters, but is missing Operational Layers and Layer Visibility support. 

Maybe we should consider adding these so templates can take advantage of them?

http://doc.arcgis.com/en/arcgis-online/reference/use-url-parameters.htm

**Comment by driskull** [comment]
Yeah, I think we talked about adding these at some point right @kellyhutchins ? Is this something we want to do?

**Comment by kellyhutchins** [comment]
I'm on the fence. I think it would require a ton of code for dealing with all the potential layer types. Not sure we want to take that on?

**Comment by driskull** [comment]
yeah, that's true. Maybe we don't have to support ALL the online viewer URL params. Only the ones we want to. It would be a pain to have to write a class that adds every layer type to a map. Seems like we would just want to promote WebMaps instead of this.

**Comment by bsvensson** [comment]
> Seems like we would just want to promote WebMaps instead of this.

+1

**Comment by alaframboise** [comment]
I guess I was just thinking the base should support all of the Map Viewer's params since it is essentially providing a "standard base" for all future templates. Right now it supports most of them.

I guess the question is: Will the 4.x Map Viewer even use these params? If not I maybe we should remove all params support from the base and just let app template developers define their own at the app-level.

**Comment by bsvensson** [comment]
I'm pretty sure 4.x MapViewer will continue to support the same params.  Keep in mind that the MapViewer is both a viewing and creating tool (as in creating webmaps), while the templates are primarily for viewing (webmaps/webscenes). So I think it makes sense that things like `basemapUrl` are not supported in templates/apps (that don't create webmaps).

Note that WAB also has (pretty similar) viewing-ish URL parameters:
http://doc.arcgis.com/en/web-appbuilder/manage-apps/app-url-parameters.htm and https://developers.arcgis.com/web-appbuilder/guide/xt-app-url-parameters-for-dev.htm.

I think it's beneficial for the platform to keep app URL params consistent, which we've been trying to do [for a while](http://resources.arcgis.com/en/help/flex-viewer/concepts/index.html#/Viewer_URL_parameters/01m300000029000000/) :)

**Comment by driskull** [comment]
>  So I think it makes sense that things like basemapUrl are not supported in templates/apps (that don't create webmaps).

I agree. I'll remove the basemap setting functions.
