### ISSUE TITLE
_getEsriEnviromentPortalUrl always returns at line 495

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-base-js#15]
Testing out the boilerplate on dev and if I set isEsri to true then the code below executes but it looks like there is an issue setting the value of appLocationIndex. I think the conditional true value should be isEsriAppsPath and the conditional false should be isEsriHomePath. 

`
.....
    const isEsriAppsPath = esriAppsPathIndex !== -1 ? true : false;
    const isEsriHomePath = esriHomePathIndex !== -1 ? true : false;
    const appLocationIndex = isEsriAppsPath ? esriAppsPathIndex : isEsriHomePath ? esriHomePathIndex : null;

    if (!appLocationIndex) {
      return;
    }
.....
  }`

Or maybe we just need to check for appLocationIndex being -1 before return? Because currently we are checking for ! (some numeric value).

**Comment by driskull** [comment]
@kellyhutchins can you test now?

**Comment by kellyhutchins** [comment]
@driskull  looks ok so I merged the updates into Nick's gallery code. I'll double-check on dev after the build and verify. 

Thanks

**Comment by driskull** [comment]
cool thanks!

**Comment by kellyhutchins** [comment]
Tested on dev and it looks good. Thanks!
