### ISSUE TITLE
Errors in TypeScript after updating to TS version 2.4

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/application-base-js#16]
After updating to TS 2.4 transpiling declareDecartor.ts returns the following errors: 

 error TS2322: Type '<TFunction extends Function>(target: Functio
n) => DeclareConstructor<any>' is not assignable to type 'ClassDecorator'.
  Type 'DeclareConstructor<any>' is not assignable to type 'void | TFunction'.
    Type 'DeclareConstructor<any>' is not assignable to type 'TFunction'.

Seems to be due to the stricter checking for generic functions that happens at 2.4 - see doc here: 
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

Using tsc --noStrictGenericChecks clears the error and so does using any for example: 

`  return function (target: Function) {
    return <any>declare(mixins, target.prototype);
  };`

**Comment by kellyhutchins** [comment]
@driskull installed this update - when you get a chance can you take a look .

**Comment by driskull** [comment]
Looks good!
