### ISSUE TITLE
Use async/await in load() method

### ISSUE THREAD

**Issue by driskull** [Esri/application-base-js#22]
There's a lot of nested promises in this method that could be improved by using async/await.

**Comment by kellyhutchins** [comment]
It's been on my to-do list for a while... hopefully soon. The only issue is that we'll need a polyfill for IE11.

**Comment by driskull** [comment]
Yeah I still need to do this for a lot of widget VM code but maybe this is a good starting place.

**Comment by driskull** [comment]
This may be a good project for someone to get started with some of this code.

**Comment by kellyhutchins** [comment]
I was going to do this at the last release but I am sort of on the fence because we'll need the polyfill for IE 11. What are your thoughts on including the polyfill?  We do it in some of the recent configurable apps so it's probably fine. @driskull

**Comment by driskull** [comment]
yeah, maybe its not worth it at this time then.

**Comment by rslibed** [comment]
Are we good to close this issue? `Async/await` implemented in PR #30

**Comment by kellyhutchins** [comment]
Yep
