### ISSUE TITLE
Enhancement to support case-insensitive URL parameters

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/application-base-js#8]
ApplicationBase.json and the app have case-sensitive URL parameters.  We’ve had user problems because people are used to generally ignoring case in the URL, so case-sensitive query parameters get mistyped.  

Can we change `map[key`] in `_urlToObject()` to `map[key.toLowerCase()]` and the `urlParams` list in ApplicationBase.json to all lowercase?

**Comment by driskull** [comment]
👍

**Comment by driskull** [comment]
Actually, I don't think we want to do this because these values get mixed into the config. things like `basemapUrl` need to be the correct case to be easily mixed in.
